x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: rotour/judge0-workers:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./active.rb:/api/db/languages/active.rb:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.judge.rule=Host(`judge.raltech.school`)"
      - "traefik.http.routers.judge.entrypoints=websecure"
      - "traefik.http.routers.judge.tls=true"
      - "traefik.http.routers.judge.tls.certresolver=letsencrypt"
      - "traefik.http.services.judge.loadbalancer.server.port=2358"
      - "traefik.http.services.judge.loadbalancer.server.scheme=http"
      - "traefik.http.middlewares.judge-stripprefix.stripprefix.prefixes=/judge0"
      - "traefik.http.routers.judge.middlewares=judge-stripprefix"
    networks:
      - traefik-net
      - default

  workers:
    image: rotour/judge0-workers:1.13.1
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
      - ./active.rb:/api/db/languages/active.rb:ro
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - default

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
    networks:
      - default

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always
    networks:
      - default

volumes:
  data:

networks:
  traefik-net:
    external: true
  default: